# -*- coding: utf-8 -*-
# Building A (office) calculation report - same format as Building B (helpers reused from build_report_B.py).
import sys, os, json, re
SC=__import__("os").environ.get("MG_WORKDIR", ".")   # working data folder (JSON / PNG in and out)
src=open(__import__("os").path.join(__import__("os").path.dirname(__import__("os").path.abspath(__file__)),"build_report_B.py"),encoding="utf-8").read()
helpers=src[:src.index("# ==================== CONTENT")]
helpers=helpers.replace('OUTDIR=r"C:\\Workspace\\##2026\\20260917 - Samutsongkram\\calculation report\\Building B"',
                        'OUTDIR=r"C:\\Workspace\\##2026\\20260917 - Samutsongkram\\calculation report\\Building A"')
helpers=helpers.replace('"Structural Calculation Report - Building B.docx"','"Structural Calculation Report - Building A.docx"')
helpers=helpers.replace('B=json.load(open(SC+"/B_data.json")); E=json.load(open(SC+"/elf_B.json"))','B=json.load(open(SC+"/A_data.json")); E=json.load(open(SC+"/elf.json"))')
helpers=helpers.replace('RM=json.load(open(SC+"/fs_rooms.json",encoding="utf-8")); LLJ=json.load(open(SC+"/fs_LL.json",encoding="utf-8"))','')
helpers=helpers.replace('IMG=SC+"/Bimg"','IMG=SC+"/Aimg"')
exec(helpers)
from docx.shared import Inches
DL,SDL,LL=T['DL(ST)'][2],T['SDL(ST)'][2],T['LL(ST)'][2]
CB=B["lcom_conc"]
def comb(name): return sum(f*T[f"{c}(ST)"][2] for c,f,a in CB[name][1])
SVC=comb("cLCB12"); U=comb("cLCB2")

# ==================== CONTENT ====================
para("Building A – Office Building",bold=True,size=20,align=WD_ALIGN_PARAGRAPH.CENTER)
para("Finite Element Analysis and RC Member Design (MIDAS GEN NX)",bold=True,size=16,align=WD_ALIGN_PARAGRAPH.CENTER)
para(); tof(); page_break()

# 1 MODEL
h1("1. Structural Model")
body_("Building A is a reinforced-concrete moment-frame office building of four suspended floors and a roof, modelled in MIDAS GEN NX with "
      "beam elements (columns and beams) and plate elements (floor slabs), and analysed by linear static analysis. Columns stand on pile caps "
      "at −1.50 m (19 supports).")
c=B["counts"]; S=B["sect"]
colsec=", ".join(v[0] for k,v in S.items() if 101<=int(k)<=107); bmsec=", ".join(v[0] for k,v in S.items() if 201<=int(k)<=212)
table(["Item","Value"],[
    ["Nodes",f"{c['nodes']:,}"],["Elements (total)",f"{c['elems']:,}"],["  Beam elements (columns, beams)",f"{c['beam']:,}"],
    ["  Plate elements (slabs, t = 180 mm)",f"{c['plate']:,}"],
    ["Levels","Base −1.50 · 2F (GF slab) +0.30 · 3F +3.80 · 4F +7.50 · 5F +10.70 · Roof +13.70 m"],
    ["Supports",f"{len(B['sup'])} supports at pile caps (−1.50 m)"],["Columns",colsec],["Beams",bmsec],
    ["Concrete","C280 (f'c = 27.5 MPa)"],["Reinforcement","SD40 (fy = 390 MPa)"],
    ["Analysis / design","Linear static; RC member checks in MIDAS GEN NX (ACI 318M-19) and MIDAS Design+ (ACI 318M-14)"]],widths=[2.4,4.2])
figure(IMG+"/geom_iso.png","3D structural model – isometric view")
figure(IMG+"/geom_front.png","Structural model – front elevation")
figure(IMG+"/geom_side.png","Structural model – side elevation")

# 2 LOADS
page_break(); h1("2. Design Loads")
h2("2.1 Gravity loads")
body_(f"DL is the self-weight of all members generated by MIDAS (total {f1(DL)} kN). SDL and LL are applied as uniform pressures on the slab "
      f"plates, as listed below (totals SDL {f1(SDL)} kN, LL {f1(LL)} kN).")
lv={}
for L,case,q,a in B["slabload"]: lv.setdefault(L,{})[case]=(q,a)
rows=[[L,f"{d['SDL'][0]:.2f}",f"{d['LL'][0]:.2f}",f"{d['SDL'][1]:.1f}",f"{d['SDL'][0]*d['SDL'][1]:.1f}",f"{d['LL'][0]*d['LL'][1]:.1f}"] for L,d in lv.items()]
table(["Level","SDL (kN/m²)","LL (kN/m²)","Slab area (m²)","SDL (kN)","LL (kN)"],rows,widths=[1.5,1.0,1.0,1.1,1.0,1.0],
      totals=["Total","","",f"{sum(d['SDL'][1] for d in lv.values()):.1f}",f1(sum(d['SDL'][0]*d['SDL'][1] for d in lv.values())),f1(sum(d['LL'][0]*d['LL'][1] for d in lv.values()))])
h2("2.2 Seismic load")
body_(f"Equivalent static seismic loads EQX and EQY per DPT 1301/1302-64 (Bangkok-Basin Zone 3), with the seismic weight from "
      f"1.0 DL + 1.0 SDL + 0.25 LL. Base shear from the analysis: {E['Vanal']:.1f} kN in each direction; the ELF calculation is in Section 6.")
h2("2.3 Load combinations")
body_("The concrete-design load combinations stored in the model follow the Ministerial Regulation B.E. 2566: Clause 7 (strength) and "
      "Clause 6 (service). D = DL + SDL.")
table(["Name","Combination","Factors in model"],[[n,d,(" + ".join(f"{f:g}{c}" for c,f,a in t)).replace("+ -","− ")] for n,(d,t) in CB.items()],
      widths=[0.8,2.4,3.4],size=11)

# 3 BEHAVIOUR
page_break(); h1("3. Model Behaviour Verification")
Dp=B["disp"]
body_(f"Under the service combination cLCB12 (D + L) the maximum vertical deflection is {Dp['SVC_DZ']*1000:.1f} mm. Under the seismic load cases the "
      f"structure sways smoothly over its height, with a maximum lateral displacement of {Dp['EQX']*1000:.1f} mm in X and {Dp['EQY']*1000:.1f} mm in Y.")
figure(IMG+"/disp_SVC.png","Vertical displacement contour (D_Z) with deformed shape – service combination cLCB12 (D + L)")
figure(IMG+"/disp_SVC_side.png","Vertical displacement contour (D_Z) with deformed shape – cLCB12, elevation")
figure(IMG+"/disp_EQX.png","Lateral displacement contour (D_X) with deformed shape – seismic EQX")
figure(IMG+"/disp_EQY.png","Lateral displacement contour (D_Y) with deformed shape – seismic EQY")

# 4 REACTIONS
page_break(); h1("4. Support Reactions – Gravity")
body_(f"Base reactions at the {len(B['sup'])} supports (kN). Combination values are obtained from the load-case results with the factors of the stored "
      "combinations cLCB12 (service) and cLCB2 (factored).")
table(["Load case / combination","ΣF_X","ΣF_Y","ΣF_Z"],[
    ["DL – self weight",*[f1(x) for x in T['DL(ST)']]],["SDL – superimposed dead",*[f1(x) for x in T['SDL(ST)']]],["LL – live",*[f1(x) for x in T['LL(ST)']]],
    ["cLCB12 – service D + L","–","–",f1(SVC)],["cLCB2 – 1.4D + 1.7L","–","–",f1(U)]],widths=[3.0,1.2,1.2,1.4])
h2("Reaction at each support (kN)")
def rz(lc,n): return next(float(r["FZ"]) for r in B["react"][lc] if int(r["Node"])==n)
rows=[]; s=u=0
for n in sorted(B["sup"],key=lambda k:(-B["sup"][k][1],B["sup"][k][0])):
    x,y,z=B["sup"][n]; n=int(n); d=rz('DL(ST)',n)+rz('SDL(ST)',n); l=rz('LL(ST)',n); s+=d+l; u+=1.4*d+1.7*l
    rows.append([f"N{n}",f"{x:.2f}",f"{y:.2f}",f"{d:.1f}",f"{l:.1f}",f"{d+l:.1f}",f"{1.4*d+1.7*l:.1f}"])
table(["Support","X (m)","Y (m)","D = DL+SDL","LL","D + L","1.4D + 1.7L"],rows,widths=[0.8,0.75,0.75,1.1,0.9,1.0,1.0],size=11,
      totals=[f"TOTAL ({len(rows)})","","",f1(DL+SDL),f1(LL),f1(s),f1(u)])
figure(IMG+"/react_SVC.png","Support reactions with values – service combination cLCB12, vertical F_Z (kN)")
figure(IMG+"/react_U.png","Support reactions with values – factored combination cLCB2, vertical F_Z (kN)")

# 5 LATERAL
page_break(); h1("5. Lateral Analysis – Seismic")
Vx=abs(T['EQX(ST)'][0]); Vy=abs(T['EQY(ST)'][1])
table(["Direction","Base shear V (kN)","Max lateral displacement (mm)"],[["EQX (X)",f1(Vx),f"{Dp['EQX']*1000:.1f}"],["EQY (Y)",f1(Vy),f"{Dp['EQY']*1000:.1f}"]],widths=[1.4,2.0,2.6])
h2("Storey drift")
Cd=4.5; I=E["I"]
body_(f"Storey drift is the relative lateral displacement between storey levels along each column line divided by the storey height; the largest "
      f"value in each storey is reported. Design drift Δ = Cd·δe/I with Cd = {Cd} (intermediate RC moment frame) and I = {I:.2f}; allowable storey "
      f"drift 0.020·hsx (DPT 1301/1302, risk categories I–II).")
rows=[]
for k in ["5F -> Roof","4F -> 5F","3F -> 4F","2F (GF slab) -> 3F","Base -> 2F (GF slab)"]:
    for lc,dn in (("EQX(ST)","X"),("EQY(ST)","Y")):
        d=B["drift"][lc][k]; des=Cd*d["ratio"]/I
        rows.append([f"{k.replace('->','→')} ({dn})",f"{d['h']:.2f}",f"{d['dmm']:.2f}",f"{100*d['ratio']:.3f}",f"{100*des:.2f}","2.00","OK" if des<=0.02 else "Exceeds"])
table(["Storey (direction)","h (m)","δe (mm)","δe/h (%)","Cd·δe/(I·h) (%)","Allow. (%)","Check"],rows,widths=[1.8,0.6,0.75,0.8,1.1,0.8,0.75],size=11)

# 6 ELF
page_break(); h1("6. Seismic – Equivalent Lateral Force (ELF) Calculation")
body_("Base shear V = Cs·W (DPT 1301/1302-64 eq. 3.2-1) with Cs = Sa·I/R (eq. 3.2-2, minimum 0.01). Samut Songkhram lies in Bangkok-Basin "
      "seismic Zone 3; Sa is taken from Table 1.4-5 (5% damping).")
h2("(a) Design seismic parameters")
table(["Parameter","Value","Reference"],[
    ["Site / basin zone","Samut Songkhram – Bangkok Basin Zone 3","zoning map"],["S_DS = Sa(0.2 s)",f"{E['SDS']:.3f} g","Table 1.4-5"],
    ["S_D1 = Sa(1.0 s)",f"{E['SD1']:.3f} g","Table 1.4-5"],["Height H","13.4 m (GF +0.30 → Roof +13.70)","–"],
    ["Period T = 0.02·H",f"{E['T']:.3f} s","eq. 3.3-1"],["Ts = S_D1/S_DS",f"{E['Ts']:.3f} s","–"],["Sa (T ≤ Ts → Sa = S_DS)",f"{E['Sa']:.3f} g","Table 1.4-5"],
    ["Importance factor I",f"{E['I']:.2f}","–"],["Response modification R","5 (intermediate RC moment frame)","–"],["Cs = Sa·I/R",f"{E['Cs']:.4f}","eq. 3.2-2"]],widths=[2.6,2.6,1.4])
h2("(b) Seismic weight, base shear and vertical distribution")
rows=[[E["names"][i],f"{E['z'][i]:+.2f}",f"{E['hx'][i]:.2f}",f1(E['Wself'][i]+E['Wsdl'][i]),f1(0.25*E['Wll'][i]),f1(E['Wseis'][i]),f"{E['whk'][i]/sum(E['whk']):.3f}",f1(E['Fx'][i]),f1(E['Vx'][i])] for i in range(4,-1,-1)]
table(["Level","z (m)","hx (m)","DL+SDL (kN)","0.25LL (kN)","wx (kN)","Cvx","Fx (kN)","Vx (kN)"],rows,widths=[0.8,0.6,0.6,0.9,0.8,0.85,0.55,0.7,0.7],size=11,
      totals=["Σ","","",f1(sum(E['Wself'])+sum(E['Wsdl'])),f1(0.25*sum(E['Wll'])),f1(E['Wtot']),"1.000",f1(sum(E['Fx'])),"–"])
body_(f"V = Cs·W = {E['Cs']:.4f} × {E['Wtot']:,.1f} = {E['V']:,.1f} kN; base shear from the MIDAS analysis {E['Vanal']:.1f} kN "
      f"({100*abs(E['V']-E['Vanal'])/E['V']:.1f}% difference). Fx = Cvx·V with k = 1 (T ≤ 0.5 s); hx measured from the support level (−1.50 m).")

# 7 MEMBER DESIGN
page_break(); h1("7. RC Member Design")
body_("Beams, columns and footings are checked with the concrete-design combinations cLCB1–cLCB24. Single-member strength checks are from "
      "MIDAS GEN NX (ACI 318M-19); member and footing summaries are from MIDAS Design+ (ACI 318M-14).")
L=json.load(open(SC+"/dsgnA/list.json"))
SINGLE={"B20000":"B2 250×600 (section 203)","B20001":"B3 200×800 (section 205)","B20002":"B5 200×500 (section 208)","B20003":"B6 250×500 (section 209)",
        "B20004":"B6C 250×500 (section 210)","B20005":"LB1 200×1600 (section 212)","C30000":"C3 200×400, ground floor (section 105)","C30001":"C3 250×500, footing stub (section 106)"}
def pretty(n):
    m=re.match(r"Summary_RC_(Beam & Girder|Column|Footing)_(.+?)(?:_(\d+))?$",n)
    kind={"Beam & Girder":"Beam","Column":"Column","Footing":"Footing"}[m.group(1)]; nm=m.group(2).replace("x","×"); pg=m.group(3)
    nm=re.sub(r"\((\d+)\)$",r"",nm).strip()
    return kind,nm,pg
for sub,ttl in (("Beam","7.1 Beams"),("Column","7.2 Columns"),("Footing","7.3 Footings")):
    page_break(); h2(ttl)
    for d in [x for x in L if x["sub"]==sub]:
        if d["name"] in SINGLE:
            cap=("RC beam strength check – " if sub=="Beam" else "RC column strength check – ")+SINGLE[d["name"]]
        else:
            kind,nm,pg=pretty(d["name"]); tot=sum(1 for x in L if x["sub"]==sub and x["name"] not in SINGLE and pretty(x["name"])[1]==nm)
            cap=f"{kind} design summary – {nm}"+(f" (page {int(pg)} of {tot})" if pg else "")
        figure(SC+"/"+d["png"],cap,width=5.9); page_break()

# NOTES
h2("Notes")
for n in ["All model data and results are extracted from the live MIDAS GEN NX model after linear static analysis.",
          "Units: kN, m unless stated. Supports at the pile caps (−1.50 m).",
          "Load combinations are those stored in the model for concrete design (cLCB1–cLCB24), per Ministerial Regulation B.E. 2566 Clauses 6 and 7; D = DL + SDL.",
          f"Seismic: DPT 1301/1302-64, Bangkok-Basin Zone 3, S_DS = {E['SDS']:.3f} g, I = {E['I']:.2f}, R = 5, Cs = {E['Cs']:.4f}.",
          "Member design pages are the MIDAS GEN NX / MIDAS Design+ outputs for the beam, column and footing groups."]:
    bullet(n)
doc.save(OUT); print("SAVED",OUT,"figures",FIGN[0])
